### PR TITLE
Made some minor import and Python 2 to 3 updates

### PR DESCRIPTION
**Pull request by aliciacanipe**
This PR is just for minor import and Python 2 to 3 updates I made to fix some of the errors I encountered while getting the superbias_create script to run. 

@bhilbert4 can you just double check that you're okay with the changes?

### CODE REVIEW

**Comment by aliciacanipe** [comment]
Uh oh. This is the first time I've encountered conflicts ...

**Comment by bhilbert4** [comment]
Although I guess there are conflicts, which is interesting...

**Comment by bhilbert4** [comment]
Conflicts look pretty trivial. Let me know if you need any help with the process of removing them.

**Comment by aliciacanipe** [comment]
Okay, I think I fixed the conflicts (it seems like it was just a weird issue with extra spaces?). @bhilbert4 are you okay with me merging this?

**Comment by bhilbert4** [comment]
Yeah, go for it!

**Pull request merged**
